apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: biginfinity8/book-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DefaultConnection
              value: "Server=book-sql-server,1433;Database=BookDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: NodePort
  selector:
    app: book-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
